name: Daily Leme Claim
on:
  schedule:
    - cron: '30 2 * * *' # ساعت ۶ صبح ایران
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install requests
      - run: python claim_script.py
